name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.APP_NAME }}:latest
            ghcr.io/${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.APP_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '[".kubernetes/01-app-deployment.yml"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          APP_NAME: ${{ secrets.APP_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          API_KEY: ${{ secrets.USERS_SERVICE_API_KEY }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          FB_PRIVATE_KEY_ID: ${{ secrets.FB_PRIVATE_KEY_ID }}
          FB_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
          FB_CLIENT_ID: ${{ secrets.FB_CLIENT_ID }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: "usersdb"  # or ${{ secrets.DB_NAME }}

      - name: Update deployment
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f .kubernetes/01-app-deployment.yml
