on:
  push:
    branches:
      - main

name: CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_NICO }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL_NICO }}
          usedocker: true
        env:
          HD_DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
