on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FB_TOKEN: ${{ secrets.FB_TOKEN }}
      FB_PRIVATE_KEY_ID: ${{ secrets.FB_PRIVATE_KEY_ID }}
      FB_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
      FB_CLIENT_ID: ${{ secrets.FB_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter and tests
        run: |
          touch .env
          docker-compose --profile test up --exit-code-from test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: coverage/

