on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter and tests
        run: docker-compose --profile test up --exit-code-from test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: coverage/

